# Explore here

In [2]:
import pandas as pd  # Import the pandas library and give it the alias 'pd' for easier access.

# Load a dataset of movies from a specified URL into a pandas DataFrame called 'movies'.
# The dataset is in CSV (Comma-Separated Values) format.
movies = pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_movies.csv")

# Load a dataset of movie credits from another specified URL into a pandas DataFrame called 'credits'.
# This dataset also is in CSV format and includes information like cast and crew for the movies.
credits = pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_credits.csv")

# Display the first 5 rows of the 'movies' DataFrame to provide a quick overview of the data it contains.
# This is useful for verifying the structure of the DataFrame, the type of data it holds, and if it was loaded correctly.
movies.head()

/tmp/ipykernel_372/3126363669.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd  # Import the pandas library and give it the alias 'pd' for easier access.

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [3]:
# Display the first 5 rows of the 'credits' DataFrame to provide a quick overview of the data it contains.
# This is useful for checking the structure of the DataFrame, the type of data it holds, and ensuring it was loaded correctly.
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
import sqlite3  # Import the sqlite3 library to interact with SQLite databases.

# Establish a connection to a SQLite database. The database is located in the 'data' directory,
# and is named 'movies_database.db'. If the database does not exist, it will be created.
conn = sqlite3.connect("../data/movies_database.db")

# Convert the 'movies' DataFrame into a SQL table within the connected SQLite database.
# The table will be named 'movies_table'. If this table already exists, it will be replaced.
# 'index = False' indicates that the DataFrame's index will not be written to the SQL table.
movies.to_sql("movies_table", conn, if_exists = "replace", index = False)

# Similarly, convert the 'credits' DataFrame into a SQL table named 'credits_table' within the same database.
# The table is replaced if it already exists, and the DataFrame's index is not included in the SQL table.
credits.to_sql("credits_table", conn, if_exists = "replace", index = False)

4803

In [5]:
# Define a SQL query to merge two tables: 'movies_table' and 'credits_table'.
# The merging is done through an INNER JOIN based on the 'title' column, meaning only rows with matching titles in both tables will be included.
query = """
    SELECT *
    FROM movies_table
    INNER JOIN credits_table
    ON movies_table.title = credits_table.title;
"""

# Execute the SQL query using the established database connection 'conn'.
# The result of this query is stored in a new DataFrame called 'total_data'.
# This DataFrame now contains combined information from both the 'movies' and 'credits' DataFrames based on movie titles.
total_data = pd.read_sql_query(query, conn)

# Close the connection to the SQLite database now that the necessary data has been retrieved.
# This is important to free up database resources and avoid potential database locks.
conn.close()

# Remove duplicate columns from the 'total_data' DataFrame.
# 'total_data.columns.duplicated()' returns a boolean array where True indicates a duplicate column.
# The '~' operator inverts the boolean values, so True becomes False and vice versa.
# 'total_data.loc[:, ~total_data.columns.duplicated()]' selects all rows and only columns that are not duplicated.
total_data = total_data.loc[:, ~total_data.columns.duplicated()]

# Display the first 5 rows of the 'total_data' DataFrame to provide an overview of the merged data,
# ensuring that the merge was successful and the dataset is as expected.
total_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
import json  # Import the json library for parsing JSON data.

# Define a function that attempts to load a JSON string safely.
# If the JSON loading fails due to a TypeError or a JSONDecodeError, it returns a default value instead.
def load_json_safe(json_str, default_value = None):
    try:
        return json.loads(json_str)  # Try to parse the JSON string.
    except (TypeError, json.JSONDecodeError):  # If parsing fails, catch the exception.
        return default_value  # Return the default value in case of an exception.

# Transform the 'genres' column: parse the JSON data and replace it with a list of genre names.
# If the original data is not NaN, it's parsed and the names are extracted; otherwise, None is assigned.
total_data["genres"] = total_data["genres"].apply(lambda x: [item["name"] for item in json.loads(x)] if pd.notna(x) else None)

# Similar transformation is applied to the 'keywords' column, extracting a list of keyword names from the JSON data.
total_data["keywords"] = total_data["keywords"].apply(lambda x: [item["name"] for item in json.loads(x)] if pd.notna(x) else None)

# For the 'cast' column, parse the JSON data, but only keep the names of the first three cast members.
# This is done by slicing the list to the first 3 elements after parsing and extracting names.
total_data["cast"] = total_data["cast"].apply(lambda x: [item["name"] for item in json.loads(x)][:3] if pd.notna(x) else None)

# Transform the 'crew' column to only include the names of the directors.
# It uses the 'load_json_safe' function to parse the JSON and then filters for crew members with the job 'Director'.
total_data["crew"] = total_data["crew"].apply(lambda x: " ".join([crew_member['name'] for crew_member in load_json_safe(x) if crew_member['job'] == 'Director']))

# The 'overview' column is transformed into a list containing the original overview string.
# This could be for consistency in data structure or further processing needs.
total_data["overview"] = total_data["overview"].apply(lambda x: [x])

# Display the first 5 rows of the transformed 'total_data' DataFrame to verify the transformations.
total_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[Action, Adventure, Fantasy, Science Fiction]",http://www.avatarmovie.com/,19995,"[culture clash, future, space war, space colon...",en,Avatar,"[In the 22nd century, a paraplegic Marine is d...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",James Cameron
1,300000000,"[Adventure, Fantasy, Action]",http://disney.go.com/disneypictures/pirates/,285,"[ocean, drug abuse, exotic island, east india ...",en,Pirates of the Caribbean: At World's End,"[Captain Barbossa, long believed to be dead, h...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[Johnny Depp, Orlando Bloom, Keira Knightley]",Gore Verbinski
2,245000000,"[Action, Adventure, Crime]",http://www.sonypictures.com/movies/spectre/,206647,"[spy, based on novel, secret agent, sequel, mi...",en,Spectre,[A cryptic message from Bondâ€™s past sends him ...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",Sam Mendes
3,250000000,"[Action, Crime, Drama, Thriller]",http://www.thedarkknightrises.com/,49026,"[dc comics, crime fighter, terrorist, secret i...",en,The Dark Knight Rises,[Following the death of District Attorney Harv...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[Christian Bale, Michael Caine, Gary Oldman]",Christopher Nolan
4,260000000,"[Action, Adventure, Science Fiction]",http://movies.disney.com/john-carter,49529,"[based on novel, mars, medallion, space travel...",en,John Carter,"[John Carter is a war-weary, former military c...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",Andrew Stanton

In [7]:
# Ensure each element in the 'overview' list is a string, even if it was originally of a different type.
total_data["overview"] = total_data["overview"].apply(lambda x: [str(x)])

# Convert each genre in the 'genres' list to a string, to ensure consistency and avoid potential type-related errors.
total_data["genres"] = total_data["genres"].apply(lambda x: [str(genre) for genre in x])

# Convert each keyword in the 'keywords' list to a string, for consistency and to handle any non-string types.
total_data["keywords"] = total_data["keywords"].apply(lambda x: [str(keyword) for keyword in x])

# Ensure each actor name in the 'cast' list is converted to a string, to standardize the data format.
total_data["cast"] = total_data["cast"].apply(lambda x: [str(actor) for actor in x])

# Convert each crew member's name in the 'crew' list to a string, to unify the data type across the column.
total_data["crew"] = total_data["crew"].apply(lambda x: [str(crew_member) for crew_member in x])

# Concatenate the lists from 'overview', 'genres', 'keywords', 'cast', and 'crew' columns into a single list in a new column 'tags'.
# Each element of these lists is then joined into a single string, with spaces between each element, effectively creating a 'bag of words'.
total_data["tags"] = total_data["overview"] + total_data["genres"] + total_data["keywords"] + total_data["cast"] + total_data["crew"]
total_data["tags"] = total_data["tags"].apply(lambda x: ",".join(x).replace(",", " "))

# Drop the original columns ('genres', 'keywords', 'cast', 'crew', 'overview') from 'total_data',
# as their information has been consolidated into the 'tags' column.
total_data.drop(columns = ["genres", "keywords", "cast", "crew", "overview"], inplace = True)

# Display the 'tags' content for the first row of the 'total_data' DataFrame.
# This shows the combined information of the dropped columns as a single string, which might be used for text analysis or as metadata.
total_data.iloc[0].tags

"['In the 22nd century  a paraplegic Marine is dispatched to the moon Pandora on a unique mission  but becomes torn between following orders and protecting an alien civilization.'] Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver J a m e s   C a m e r o n"

In [8]:
# Export the 'total_data' DataFrame to a CSV file, effectively saving the processed and transformed data.
# The file is saved to the 'processed' subdirectory within 'data', and is named 'clean_data.csv'.
# 'index = False' ensures that the DataFrame index is not included in the CSV file, only the data.
total_data.to_csv("../data/processed/clean_data.csv", index = False)

# Re-establish a connection to the SQLite database located in the 'data' directory, named 'movies_database.db'.
# This connection is used to save the transformed data back into the database.
conn = sqlite3.connect("../data/movies_database.db")

# Convert the 'movies' DataFrame (which may still contain the original unprocessed data) into a SQL table within the database.
# The table is named 'clean_movies_data'. If this table already exists, it is replaced with the current version of the 'movies' DataFrame.
# 'index = False' specifies that the DataFrame's index should not be included as a column in the SQL table.
movies.to_sql("clean_movies_data", conn, if_exists = "replace", index = False)

4803

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer  # Import TfidfVectorizer for text vectorization.
from sklearn.neighbors import NearestNeighbors  # Import NearestNeighbors for the KNN model.

# Initialize a TfidfVectorizer object to convert the text data into a matrix of TF-IDF features.
vectorizer = TfidfVectorizer()
# Fit the vectorizer to the 'tags' column of 'total_data' and transform the text into a TF-IDF matrix.
tfidf_matrix = vectorizer.fit_transform(total_data["tags"])

# Initialize a NearestNeighbors model specifying the number of neighbors, the algorithm to use, and the metric.
# 'n_neighbors = 6' means the model will find the 6 nearest neighbors.
# 'algorithm = "brute"' specifies to use the brute-force search.
# 'metric = "cosine"' sets the cosine similarity as the distance metric to measure similarity between vectors.
model = NearestNeighbors(n_neighbors = 6, algorithm = "brute", metric = "cosine")
# Fit the KNN model to the TF-IDF matrix, effectively preparing it to find nearest neighbors in this feature space.
model.fit(tfidf_matrix)

# Define a function to get movie recommendations based on the title of a movie.
def get_movie_recommendations(movie_title):
    # Find the index of the movie in 'total_data' that matches the given title.
    movie_index = total_data[total_data["title"] == movie_title].index[0]
    # Use the KNN model to find the distances and indices of the 6 nearest neighbors to the given movie.
    distances, indices = model.kneighbors(tfidf_matrix[movie_index])
    # Construct a list of similar movies, excluding the first one (which is the input movie itself).
    similar_movies = [(total_data["title"][i], distances[0][j]) for j, i in enumerate(indices[0])]
    return similar_movies[1:]  # Return the list of recommendations, excluding the input movie.

# Specify a movie title to get recommendations for.
input_movie = "How to Train Your Dragon"
# Get the list of recommended movies for the input title using the defined function.
recommendations = get_movie_recommendations(input_movie)

# Print out the recommendations.
print("Film recommendations for '{}'".format(input_movie))
for movie, distance in recommendations:
    # Each recommendation includes the title of the movie and its distance (a measure of similarity) from the input movie.
    print("- Film: {}".format(movie))

Film recommendations for 'How to Train Your Dragon'
- Film: How to Train Your Dragon 2
- Film: Dragon Nest: Warriors' Dawn
- Film: Pete's Dragon
- Film: George and the Dragon
- Film: Eragon

In [10]:
from pickle import dump  # Import the 'dump' function from the 'pickle' module for serializing objects.

# Serialize the trained KNN model ('model') and save it to a file using 'dump'.
# The file is saved in the 'models' directory with the name 'knn_neighbors-6_algorithm-brute_metric-cosine.sav'.
# 'wb' mode is used to write in binary format, which is required for pickling.
dump(model, open("../models/knn_neighbors-6_algorithm-brute_metric-cosine.sav", "wb"))